import type { Metadata } from "next";
import Link from "next/link";
import SectionHeader from "@/components/ui/SectionHeader";
import HudPanel from "@/components/ui/HudPanel";
import ScienceContext from "@/components/ui/ScienceContext";

export const metadata: Metadata = { title: "About | TTTS", description: "Learn what the Time Travel Theory Simulator does, where to start, and how it separates measured science from imagined stories." };

export default function AboutPage() {
  return <>
    <SectionHeader eyebrow="08 / ABOUT THIS PROJECT" title="About the Time Travel Theory Simulator" description="TTTS is a learning website for anyone curious about time travel. It combines a simple calculation with explanations and interactive stories. You do not need to know physics before you start." />
    <section aria-labelledby="creator-heading" className="mb-6">
      <HudPanel>
        <p className="eyebrow">ABOUT THE CREATOR</p>
        <h2 id="creator-heading" className="mt-3 text-2xl">Anastacia Webster</h2>
        <p className="exploration-copy max-w-3xl">I’m an aspiring software engineer who has always dreamed of turning my ideas into projects people can experience. Watching something I imagined come to life on a screen is one of the most exciting parts of learning to build software.</p>
        <h3 className="mt-6 text-xl">Why I built TTTS</h3>
        <p className="exploration-copy max-w-3xl">I’ve been fascinated by space since I was young, and that curiosity inspired me to create the Time Travel Theory Simulator. I wanted to make a fun, interactive place where anyone curious about time travel could explore ideas like time dilation, wormholes, and paradoxes at their own pace.</p>
        <p className="exploration-copy max-w-3xl">It’s the kind of project I once wished I could find—and now I get to build it.</p>
      </HudPanel>
    </section>
    <div className="theory-grid">
      <HudPanel>
        <h2 className="text-2xl">What can you learn here?</h2>
        <p className="exploration-copy">Start with a surprising real effect: two people can experience different amounts of time because of their motion or the gravity around them. This is called time dilation. For example, someone traveling very fast could age less than a person who stays on Earth.</p>
        <p className="exploration-copy">Then explore a different question: what would happen if you could visit the past? We use imagined tunnels and stories about changing history to explain the questions this raises. Exploring an idea does not mean that we know how to make it happen.</p>
      </HudPanel>
      <HudPanel>
        <h2 className="text-2xl">What does simulator mean here?</h2>
        <p className="exploration-copy">A simulator lets you change inputs and see a result based on a set of rules. Those rules matter. The Calculator uses a physics equation for motion at a steady speed. The other activities use stated assumptions, such as imagining that a tunnel through space exists.</p>
        <p className="exploration-copy">The animated portal and control panels are artwork for the learning experience. They do not detect real portals, measure the universe, or control a time machine.</p>
      </HudPanel>
      <HudPanel>
        <h2 className="text-2xl">A simple route through the site</h2>
        <p className="exploration-copy">Try the <Link className="underline" href="/calculator">Calculator</Link> to compare traveler years with Earth years. Read <Link className="underline" href="/theories">Theories</Link> for an overview of the ideas behind the site.</p>
        <p className="exploration-copy">Use <Link className="underline" href="/wormholes">Wormholes</Link> to compare a normal journey with an imagined shortcut. In <Link className="underline" href="/paradoxes">Paradoxes</Link>, try preventing your own time machine from being built and see how different story rules change the result.</p>
        <p className="exploration-copy">Visit the <Link className="underline" href="/faq">FAQ</Link> for definitions and help. You can also ask the <Link className="underline" href="/oracle">Oracle</Link> a question. It labels whether the answer was generated by Gemini, an AI service, or taken from a previously written explanation.</p>
      </HudPanel>
      <HudPanel>
        <h2 className="text-2xl">What are the limits?</h2>
        <p className="exploration-copy">The Calculator leaves out gravity, speeding up, slowing down, and turning around. It explains one relationship between speed and time, rather than predicting every part of a real space mission.</p>
        <p className="exploration-copy">The Wormholes and Paradoxes activities do not predict arrival dates, tell us whether a tunnel would stay open, or give the chance of changing the past. No part of the site demonstrates travel to an earlier event.</p>
        <p className="exploration-copy">AI answers can contain mistakes. Treat them as a starting point for learning, and check important claims against reliable science sources.</p>
      </HudPanel>
    </div>
    <ScienceContext established="Supported by measurements: clocks can record different amounts of time depending on motion and gravity. The Calculator illustrates the effect of motion under simplified conditions." theoretical="Possible in a mathematical model: researchers can describe ideas such as wormholes using equations. An equation allowing something does not show that the universe contains it." fictional="Invented for an example: a safe portal or a rule that lets history split into two versions. These help us explore a question, but are not known features of the world." />
    <HudPanel className="exploration-reading">
      <h2 className="text-2xl">Keep learning at your own pace</h2>
      <ul>
        <li><Link href="/faq">Start with the TTTS FAQ for definitions and worked examples</Link></li>
        <li><a href="https://www.einstein-online.info/en/explandict/time-dilation/">Einstein Online: a short definition of time dilation</a></li>
        <li><a href="https://arxiv.org/abs/0710.4474">An advanced research review of wormholes (uses physics and mathematics)</a></li>
      </ul>
      <p className="exploration-copy">You can use the activities on a phone or a desktop and move through the controls with a keyboard. Select Pause motion at the top of the page if you prefer the animations to stay still. The site also follows your device setting for reduced motion.</p>
    </HudPanel>
  </>;
}
