import type { Metadata } from "next";
import Link from "next/link";
import SectionHeader from "@/components/ui/SectionHeader";
import HudPanel from "@/components/ui/HudPanel";

export const metadata: Metadata = { title: "FAQ | TTTS", description: "Beginner-friendly answers about time travel ideas, the Calculator, the Oracle, and using TTTS." };
const questions = [
  ["What is this website, and where should I start?", "TTTS stands for Time Travel Theory Simulator. It is a learning website with calculations and imagined stories you can explore. No physics background is needed. Start with the Calculator to compare how much time passes for a traveler and someone on Earth. Theories introduces related ideas. Wormholes and Paradoxes let you explore what might happen if you add rules that have not been shown to work in real life."],
  ["What do relativity and time dilation mean?", "Relativity is Einstein's description of how space, time, motion, and gravity are related. One result is that two clocks do not always record the same amount of time between events. Their motion and the gravity around them matter. This difference is called time dilation. Each person still experiences their own clock ticking normally; the difference appears when clocks or measurements are compared."],
  ["Can people really travel through time?", "Different amounts of time can pass for different people. For example, a traveler moving very fast could experience fewer years than people on Earth. This is sometimes called travel into the future: the traveler ages less while Earth advances further. The underlying clock effect has been measured, but a practical spacecraft for dramatic jumps is a different challenge. We have no demonstrated way to send someone back to an earlier event. This website cannot build or operate a time machine."],
  ["What do the science labels mean?", "Established science means an effect has evidence behind it, such as measured differences between clocks. Theoretical possibility means an idea fits some mathematical model, but that alone does not show it exists in nature. A model is a simplified description used to investigate an idea. Fictional assumption means we supply a rule for the activity, such as a safe tunnel to the past. None of these labels gives a percentage chance that time travel will work."],
  ["What numbers do I enter in the Calculator?", "Enter a speed as a fraction of the speed of light. For example, 0.5 means half the speed of light and 0.9 means 90%. Use a value from 0 up to, but not including, 1. Then enter a positive number of traveler years: the time that passes on a clock traveling with the person. Select Run Temporal Calculation to see the corresponding time in the Earth-based comparison."],
  ["How do I read the Calculator results?", "With a speed of 0.9 and 5 traveler years, the result is about 11.47 Earth years. That means the traveler's clock records 5 years while the Earth-based comparison records about 11.47 years in this simplified calculation. The Lorentz factor is the multiplier connecting those numbers: about 2.294 in this example. Multiply 5 by 2.294 to get about 11.47. At zero speed, the multiplier is 1 and the two times match."],
  ["Does the Calculator describe a complete space mission?", "No. It treats the traveler as moving at one constant speed relative to Earth. It leaves out gravity and the details of speeding up, slowing down, and turning around. It does not calculate fuel needs or tell you how to build a ship. The result explains one time effect under simple conditions, rather than planning a real journey."],
  ["Why do the results stay the same when I edit the inputs?", "They describe the values you used the last time you pressed the calculation button. Changing a box does not automatically run a new calculation. The reminder tells you to press the button again. This keeps an old result from being paired with a new explanation based on numbers you have not submitted yet."],
  ["What is a wormhole? Is it the same as a black hole?", "A wormhole is a hypothetical connection between distant places, often pictured as a tunnel. Hypothetical means proposed, rather than observed. No wormhole has been observed. A black hole is a region whose gravity is so strong that light cannot escape from inside its boundary. We have evidence for black holes, but that does not make them usable tunnels or entrances to another time."],
  ["What is a paradox, and what does branching mean?", "A paradox is a puzzle that leads to conflicting conclusions. If you travel back and stop your time machine from being built, you also remove the machine needed to make that trip. Branching is a story rule in which your change creates a separate version of history while the original still exists. That can make the story fit together, but it does not prove that separate histories are available to visit."],
  ["What does AI response · Gemini mean?", "Gemini, an artificial intelligence service, generated the answer for your question. The label identifies where the answer came from, not whether every statement is correct. Preset explanation means the app used a previously written answer because a live AI answer was unavailable. A preset may be more general than your question. Check important claims against reliable sources."],
  ["What happens when I send the Oracle a question?", "Your question goes to the computer running this website, called its server. When the AI connection is set up, the server forwards the question to Gemini for an answer. Do not put private personal information into your question. The Wormholes and Paradoxes choices run in your browser and do not send questions to Gemini."],
  ["How do I stop the animations or use the site with a keyboard?", "Select Pause motion at the top of the page to stop the decorative movement. Resume motion starts it again. Your device may also have a reduced-motion accessibility setting, which the site respects. With a keyboard, use Tab to move between controls, arrow keys to change an option within a choice group, and Enter or Space to open a FAQ answer. Pausing the animations does not stop you from using the activities."],
];

export default function FAQPage() {
  return <>
    <SectionHeader eyebrow="07 / HELP AND EXPLANATIONS" title="Frequently asked questions" description="New to these ideas? Start here for plain-language explanations, examples of Calculator results, and help using the site. Select a question to open its answer." />
    <HudPanel>{questions.map(([question, answer]) => <details className="faq-item" key={question}><summary>{question}</summary><p className="exploration-copy">{answer}</p></details>)}</HudPanel>
    <p className="science-note">Learn about <Link href="/about">the project and what it can show</Link>, or try the <Link href="/calculator">Calculator</Link>.</p>
  </>;
}
